// <auto-generated />
using System;
using KaezanArenaFable.Api.Meta.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaezanArenaFable.Api.Meta.Persistence.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260612124506_InitialPlayerState")]
    partial class InitialPlayerState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountEquipmentRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("WaifuId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.Property<string>("Slot")
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("slot");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.HasKey("AccountId", "WaifuId", "Slot");

                    b.ToTable("account_equipment", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountInventoryRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.HasKey("AccountId", "ItemId");

                    b.ToTable("account_inventory", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountMasteryPointsRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("WaifuId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Spent")
                        .HasColumnType("int")
                        .HasColumnName("spent");

                    b.HasKey("AccountId", "WaifuId");

                    b.ToTable("account_mastery_points", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountMasteryRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("WaifuId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.Property<string>("NodeId")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .HasColumnName("node_id");

                    b.HasKey("AccountId", "WaifuId", "NodeId");

                    b.ToTable("account_mastery", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("ActiveWaifuId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("active_waifu_id");

                    b.Property<string>("DailyDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("daily_date");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<long>("Kaeros")
                        .HasColumnType("bigint")
                        .HasColumnName("kaeros");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("RunsPlayed")
                        .HasColumnType("int")
                        .HasColumnName("runs_played");

                    b.Property<int>("RunsWon")
                        .HasColumnType("int")
                        .HasColumnName("runs_won");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountWaifuRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("WaifuId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.Property<int>("Ascension")
                        .HasColumnType("int")
                        .HasColumnName("ascension");

                    b.Property<int>("Shards")
                        .HasColumnType("int")
                        .HasColumnName("shards");

                    b.HasKey("AccountId", "WaifuId");

                    b.ToTable("account_waifus", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.BestiaryRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("Species")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("species");

                    b.Property<long>("Kills")
                        .HasColumnType("bigint")
                        .HasColumnName("kills");

                    b.HasKey("AccountId", "Species");

                    b.ToTable("bestiary", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.DailyChallengeScoreRow", b =>
                {
                    b.Property<string>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<long>("TimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("time_ms");

                    b.HasKey("Date", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date", "Score");

                    b.ToTable("daily_challenge_scores", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.DailyContractRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("Date")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("date");

                    b.Property<string>("ContractId")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .HasColumnName("contract_id");

                    b.Property<bool>("Claimed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("claimed");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Param")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("param");

                    b.Property<long>("Progress")
                        .HasColumnType("bigint")
                        .HasColumnName("progress");

                    b.Property<long>("Target")
                        .HasColumnType("bigint")
                        .HasColumnName("target");

                    b.HasKey("AccountId", "Date", "ContractId");

                    b.ToTable("daily_contracts", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.GachaHistoryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("BannerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("banner_id");

                    b.Property<int>("Rarity")
                        .HasColumnType("int")
                        .HasColumnName("rarity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ts");

                    b.Property<string>("WaifuId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Timestamp");

                    b.ToTable("gacha_history", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.GachaPityRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("BannerId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("banner_id");

                    b.Property<bool>("Guaranteed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("guaranteed");

                    b.Property<int>("SinceFive")
                        .HasColumnType("int")
                        .HasColumnName("since_5");

                    b.Property<int>("SinceFour")
                        .HasColumnType("int")
                        .HasColumnName("since_4");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.HasKey("AccountId", "BannerId");

                    b.ToTable("gacha_pity", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.ReplayRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<string>("CommandsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("commands_json");

                    b.Property<string>("FinalHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("final_hash");

                    b.Property<ulong>("Seed")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seed");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Timestamp");

                    b.ToTable("replays", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.RunResultRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasColumnName("kills");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("outcome");

                    b.Property<int>("RunLevel")
                        .HasColumnType("int")
                        .HasColumnName("run_level");

                    b.Property<ulong>("Seed")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("seed");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ts");

                    b.Property<string>("WaifuId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("waifu_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Timestamp");

                    b.ToTable("run_results", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.TierClearRow", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("account_id");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.Property<int>("Clears")
                        .HasColumnType("int")
                        .HasColumnName("clears");

                    b.HasKey("AccountId", "Tier");

                    b.ToTable("tier_clears", (string)null);
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountEquipmentRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountInventoryRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountMasteryPointsRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountMasteryRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.AccountWaifuRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.BestiaryRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.DailyChallengeScoreRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.DailyContractRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.GachaHistoryRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.GachaPityRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.ReplayRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.RunResultRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaezanArenaFable.Api.Meta.Persistence.TierClearRow", b =>
                {
                    b.HasOne("KaezanArenaFable.Api.Meta.Persistence.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
